const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const ui={time:document.querySelector('#time'),score:document.querySelector('#score'),energy:document.querySelector('#energy'),powers:document.querySelector('#powers'),overlay:document.querySelector('#overlay'),title:document.querySelector('#overlay-title'),copy:document.querySelector('#overlay-copy'),start:document.querySelector('#start'),sound:document.querySelector('#sound')};
const COLORS=[{name:'RED',hex:'#e80000',need:8},{name:'BLUE',hex:'#0034d1',need:18},{name:'YELLOW',hex:'#ffed00',need:32},{name:'GREEN',hex:'#467500',need:48}];
let running=false,startAt=0,last=0,score=0,energy=0,unlocked=0,spawnClock=0,mouse={x:900,y:360},keys={},shots=[],enemies=[],orbs=[],particles=[],blooms=[],shake=0,soundOn=true,bossSpawned=false;
const player={x:640,y:360,r:17,hp:100,flash:0};
ui.powers.innerHTML=COLORS.map((c,i)=>`<div class="power" id="p${i}" style="background:${c.hex}">${c.name[0]}</div>`).join('');
addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mouse.x=(e.clientX-r.left)*canvas.width/r.width;mouse.y=(e.clientY-r.top)*canvas.height/r.height});
ui.sound.onclick=()=>{soundOn=!soundOn;ui.sound.textContent=`SOUND: ${soundOn?'ON':'OFF'}`};ui.start.onclick=reset;
let audio;function tone(f=200,d=.05,type='square'){if(!soundOn)return;audio??=new AudioContext();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function reset(){running=true;startAt=performance.now();last=startAt;score=energy=unlocked=spawnClock=shake=0;bossSpawned=false;shots=[];enemies=[];orbs=[];particles=[];blooms=[];player.x=640;player.y=360;player.hp=100;COLORS.forEach((_,i)=>document.querySelector(`#p${i}`).classList.remove('on'));ui.overlay.classList.add('hidden');requestAnimationFrame(loop)}
function spawn(boss=false){const side=Math.floor(Math.random()*4);let x=side===0?-30:side===1?1310:Math.random()*1280,y=side===2?-30:side===3?750:Math.random()*720;const tier=Math.min(unlocked,3);enemies.push({x,y,r:boss?44:14+Math.random()*8,hp:boss?34:2+tier,speed:boss ? 0.6 : 1.15+tier*.16+Math.random()*.45,color:boss?'rainbow':tier?COLORS[Math.floor(Math.random()*tier)].hex:'#626262',boss,phase:Math.random()*6});}
function burst(x,y,color,n=10){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*7,vy:(Math.random()-.5)*7,life:1,color})}
function update(dt,elapsed){let dx=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0),dy=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0),m=Math.hypot(dx,dy)||1;player.x=Math.max(22,Math.min(1258,player.x+dx/m*260*dt));player.y=Math.max(22,Math.min(698,player.y+dy/m*260*dt));
  spawnClock-=dt;if(spawnClock<=0){spawn();spawnClock=Math.max(.18,.72-elapsed*.007)}if(elapsed>55&&!bossSpawned){bossSpawned=true;spawn(true);tone(75,.35,'sawtooth')}
  if(Math.floor(elapsed*7)!==Math.floor((elapsed-dt)*7)){let a=Math.atan2(mouse.y-player.y,mouse.x-player.x);shots.push({x:player.x,y:player.y,vx:Math.cos(a)*590,vy:Math.sin(a)*590,r:5+unlocked,color:unlocked?COLORS[(unlocked-1)%4].hex:'#fff',life:1.5,power:1+unlocked*.42});tone(280+unlocked*90,.025)}
  shots.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.life-=dt});shots=shots.filter(s=>s.life>0);
  enemies.forEach(e=>{e.phase+=dt*4;let a=Math.atan2(player.y-e.y,player.x-e.x);e.x+=Math.cos(a)*e.speed*70*dt;e.y+=Math.sin(a)*e.speed*70*dt;if(Math.hypot(e.x-player.x,e.y-player.y)<e.r+player.r){player.hp-=e.boss?18:8;e.x-=Math.cos(a)*40;e.y-=Math.sin(a)*40;shake=10;player.flash=.15;burst(player.x,player.y,'#fff',8)}});
  for(const s of shots)for(const e of enemies){if(e.hp>0&&Math.hypot(s.x-e.x,s.y-e.y)<s.r+e.r){e.hp-=s.power;s.life=0;burst(s.x,s.y,s.color,3);if(e.hp<=0){score+=e.boss?500:25;const count=e.boss?10:1;for(let i=0;i<count;i++)orbs.push({x:e.x,y:e.y,vx:(Math.random()-.5)*4,vy:(Math.random()-.5)*4,color:e.boss?COLORS[i%4].hex:(unlocked<COLORS.length?COLORS[unlocked].hex:'#fff')});burst(e.x,e.y,e.color==='rainbow'?'#fff':e.color,e.boss?40:12);shake=e.boss?18:4}}}
  enemies=enemies.filter(e=>e.hp>0);orbs.forEach(o=>{let a=Math.atan2(player.y-o.y,player.x-o.x),d=Math.hypot(player.x-o.x,player.y-o.y);if(d<150){o.vx+=Math.cos(a)*.55;o.vy+=Math.sin(a)*.55}o.x+=o.vx;o.y+=o.vy;if(d<25){o.dead=true;energy++;score+=10;tone(520+energy%5*70,.05,'sine')}});orbs=orbs.filter(o=>!o.dead);
  while(unlocked<COLORS.length&&energy>=COLORS[unlocked].need){const c=COLORS[unlocked];blooms.push({x:player.x,y:player.y,r:0,max:1000,color:c.hex,alpha:.24});document.querySelector(`#p${unlocked}`).classList.add('on');unlocked++;player.hp=Math.min(100,player.hp+25);burst(player.x,player.y,c.hex,45);tone(180+unlocked*140,.4,'sine')}
  blooms.forEach(b=>{b.r+=dt*450;b.alpha-=dt*.035});particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vx*=.97;p.vy*=.97;p.life-=dt*1.6});particles=particles.filter(p=>p.life>0);player.flash-=dt;shake*=.87;
}
function draw(elapsed){ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.fillStyle='#a7a7a7';ctx.fillRect(-20,-20,1320,760);
  ctx.strokeStyle='#858585';ctx.lineWidth=1;for(let x=0;x<1280;x+=64){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,720);ctx.stroke()}for(let y=0;y<720;y+=64){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1280,y);ctx.stroke()}
  blooms.forEach(b=>{ctx.globalAlpha=Math.max(0,b.alpha);ctx.fillStyle=b.color;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,7);ctx.fill()});ctx.globalAlpha=1;
  for(let i=0;i<unlocked;i++){ctx.fillStyle=COLORS[i].hex+'88';for(let k=0;k<12;k++){let x=(i*313+k*107)%1280,y=610+Math.sin(k*1.8+i)*40;ctx.fillRect(x,y,7,40);ctx.beginPath();ctx.arc(x+3,y,10+i*2,0,7);ctx.fill()}}
  orbs.forEach(o=>{ctx.shadowBlur=18;ctx.shadowColor=o.color;ctx.fillStyle=o.color;ctx.beginPath();ctx.arc(o.x,o.y,7,0,7);ctx.fill()});ctx.shadowBlur=0;
  shots.forEach(s=>{ctx.shadowBlur=22;ctx.shadowColor=s.color;ctx.fillStyle=s.color;ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,7);ctx.fill()});ctx.shadowBlur=0;
  enemies.forEach(e=>{ctx.fillStyle=e.color==='rainbow'?COLORS[Math.floor(e.phase)%4].hex:e.color;ctx.fillRect(e.x-e.r,e.y-e.r,e.r*2,e.r*2);ctx.strokeStyle='#111';ctx.lineWidth=3;ctx.strokeRect(e.x-e.r,e.y-e.r,e.r*2,e.r*2);ctx.fillStyle='#111';ctx.fillRect(e.x-e.r*.5,e.y-e.r*.25,5,5);ctx.fillRect(e.x+e.r*.25,e.y-e.r*.25,5,5)});
  ctx.fillStyle=player.flash>0?'#e80000':'#f4f4f4';ctx.fillRect(player.x-15,player.y-17,30,34);ctx.fillStyle='#161616';ctx.fillRect(player.x-12,player.y-22,24,9);ctx.fillRect(player.x-9,player.y-6,5,5);ctx.fillRect(player.x+4,player.y-6,5,5);ctx.strokeStyle='#fff';ctx.strokeRect(20,686,220,13);ctx.fillStyle=player.hp>35?'#fff':'#e80000';ctx.fillRect(23,689,214*Math.max(0,player.hp)/100,7);particles.forEach(p=>{ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,4,4)});ctx.globalAlpha=1;ctx.restore()}
function finish(win){running=false;ui.overlay.classList.remove('hidden');ui.title.textContent=win?'FULL BLOOM':'FADED';const rank=score>1700?'PRISMATIC':score>1100?'VIBRANT':score>600?'FIRST HUE':'FADED';ui.copy.textContent=`Score ${score.toString().padStart(4,'0')} · Rank: ${rank}. ${win?'The world lives again.':'The color was consumed.'}`;ui.start.textContent='BLOOM AGAIN'}
function loop(now){if(!running)return;const elapsed=(now-startAt)/1000,dt=Math.min(.033,(now-last)/1000);last=now;update(dt,elapsed);draw(elapsed);ui.time.textContent=Math.max(0,Math.ceil(60-elapsed));ui.score.textContent=score.toString().padStart(4,'0');const next=COLORS[unlocked]?.need??48;ui.energy.textContent=`${energy} / ${next}`;if(player.hp<=0)return finish(false);if(elapsed>=60)return finish(true);requestAnimationFrame(loop)}
